services:
  db:
    image: postgres:15-alpine
    container_name: fingen-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-ia:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: fingen-python
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    environment:
      - GEMINI_TOKEN=${GEMINI_TOKEN}
    volumes:
      - ./main.py:/app/main.py

  app:
    build: .
    container_name: fingen-java
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_DRIVER=org.postgresql.Driver
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PYTHON_API_URL=${PYTHON_API_URL}
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
    volumes:
      - app_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      python-ia:
        condition: service_started

volumes:
  postgres_data:
  app_uploads: